services:
  web:
    image: node:12
    user: "node"
    working_dir: /home/node/app

    ports:
        - "3000:3000"           
    volumes:
      - ./:/home/node/app 

    command: "npm start"         #Start with no testing
    #command: "npm run testandrun" #Start with testing
                                        
volumes:
  labwebsite-db: {}
